context:
  version: 2.3.1

package:
  name: vim-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/vim-language-server/-/vim-language-server-${{ version }}.tgz
  sha256: ffe0d18258a4b09bec46ec853f8838748c007c62c1fcf12d1eefedfaf19e1c46

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - "vim-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file: LICENSE
  summary: VimScript language server
  homepage: https://github.com/iamcco/vim-language-server
  repository: https://github.com/iamcco/vim-language-server

extra:
  recipe-maintainers:
    - danielnachun
